print("Welcome to the tip calculator.")
billAmt = float(input("What was the total bill?"))
tipPercentage = int(input("What percentage tip would you like to give? 10, 12 or 15?"))
noOfPeople = int(input("How many people to split the bill?"))
splitAmt = round(((1 + (int(tipPercentage)/100))*billAmt) / noOfPeople, 2)
print(f"Each person should pay: ${splitAmt}")
